### ISSUE TITLE
Move Nmag webpages

### ISSUE THREAD

**Issue by fangohr** [nmag-project/project-tasks#1]
Move https://nmag.soton.ac.uk/nmag/index.html to https://fangohr.github.io/nmag.github.io

The sources are available at https://github.com/fangohr/nmag-www

(This is a copy of https://bitbucket.org/fangohr/nmag-www/src/www/, but the suggestion is to take the github copy of the repo as the authoritative one in the future.)

- This must be made to compile (should be reasonable; needs python 2)
- ideally in a container (Docker) so it is easier for others to repeat
- Content must be updated but is separate issue (https://github.com/fangohr/nmag/issues/3)
- static html of the compiled version (than rest2www creates) to be put into the repo https://github.com/fangohr/nmag.github.io so that it appears automatically on https://nmag.github.io

**Comment by mhanberry1** [comment]
Added docker compilation:
https://github.com/fangohr/nmag-www/pull/1

**Comment by mhanberry1** [comment]
See https://github.com/fangohr/nmag.github.io/pull/1 for status on migrating code to https://nmag.github.io
