### ISSUE TITLE
Should we move the nmag homepage to `nmag-project.github.io`?

### ISSUE THREAD

**Issue by fangohr** [nmag-project/project-tasks#14]
Hi have created an organisation (https://github.com/nmag-project) which should allow us to host the Nmag webpages at nmag-project.github.io . That's probably better than https://fangohr.github.io/nmag.github.io/index.html ?

At least we have the option.

Views, @mhanberry1, Venkat?

**Comment by mhanberry1** [comment]
That's definitely the right way to go. If I remember correctly, the nmag.github.io code is ready to go. Let me know if it needs to be updated.

**Comment by fangohr** [comment]
@mhanberry1 and @venkat004 can you move the pages to the new location?

**Comment by fangohr** [comment]
Hi @mhanberry1 and @Venkat004, I have put a notice on the [current nmag home page](http://nmag.soton.ac.uk/nmag/) that we will move to a new site soon, and put a slow redirection command into the <HEAD> of the old webpage: I am hoping google may pick this up and this could help to redirect new queries in the future.

As such, it would now be good to have some (if only a dummy `Hello world - nmag to appear soon`) webpage at the new location. 

Here is the forwarding instruction (I hope I got the target URL right): 

` <meta http-equiv="Refresh" content="60; url=https://nmag-project.github.io/index.html" />`

<img width="1187" alt="Screenshot 2021-09-07 at 18 46 59" src="https://user-images.githubusercontent.com/4489119/132382017-74c91a4c-c035-404c-88a8-10a7d666d002.png">

**Comment by mhanberry1** [comment]
@fangohr I received your invitation to https://github.com/nmag-project, but unfortunately it has expired. can you send it again?
Once that is done, I'll go ahead and add the nmag.io source to that org.

**Comment by fangohr** [comment]
Done :)

**Comment by mhanberry1** [comment]
I've moved the code, so https://nmag-project.github.io/ is live now.

homepage source: https://github.com/nmag-project/nmag-project.github.io
code used to build the homepage: https://github.com/nmag-project/nmag-site
