### ISSUE TITLE
Try to setup URL redirection for disappearing server `nmag.soton.ac.uk`

### ISSUE THREAD

**Issue by fangohr** [nmag-project/project-tasks#15]
But to where? 

For now, it would have to be https://fangohr.github.io/nmag.github.io/index.html

Or we could consider a maybe better URL (see #14).

**Comment by fangohr** [comment]
I have put a redirection on the current site (see https://github.com/fangohr/nmag/issues/14#issuecomment-914465690) as a first step.

**Comment by mhanberry1** [comment]
I suggest we use the following code to redirect the site instead:
```html
 <meta http-equiv="Refresh" content="0; url=https://nmag-project.github.io/index.html" />
```

I used `0;` instead of `60;` so that the page would redirect right away instead of waiting a minute to do so.

It would be good to include a message in the body that links to the new site as well so that if a browser doesn't redirect automatically, the user can still find the new site:
```html
<p>The nmag documentation has permanently moved to <a href="https://nmag-project.github.io/index.html">https://nmag-project.github.io/index.html</a></p>
```

**Comment by mhanberry1** [comment]
...It's worth noting that the best way to do this is with an `HTTP Redirect` header via the [server configuration](https://css-tricks.com/redirect-web-page/#apache-redirects), but that's not quite as easy. It would help the new site rank higher with search engines, though.

**Comment by fangohr** [comment]
I can update the redirect message (and reduce the interval to 0 seconds) once we have the new site up and running at the final location.

The .htaccess route we can explore, but the machine is likely to be taken down in a few days. More important would be to have a redirect at University level. I'll try for this, but can't promise it will be possible.

**Comment by mhanberry1** [comment]
The site is up now. The redirect should point to https://nmag-project.github.io/

**Comment by fangohr** [comment]
That's done.

I also added the 'permanently moved' statement.

<img width="812" alt="Screenshot 2021-09-10 at 12 14 27" src="https://user-images.githubusercontent.com/4489119/132838701-96e288fe-3bbc-481d-bed9-d32924e6ce75.png">

The redirection takes a long time for me (don't know why) but eventually (after 10 seconds?) works.

**Comment by fangohr** [comment]
I also created a `.hcaccess` entry but it doesn't seem to be recognised. Maybe we can talk briefly tonight.

<pre>$ cat /var/www/.htaccess 
Redirect 301 /nmag https://nmag-project.github.io
</pre>

**Comment by mhanberry1** [comment]
> I also created a `.hcaccess` entry but it doesn't seem to be recognised. Maybe we can talk briefly tonight.

It's probably not enabled on the server. There would need to be an `AllowOverride All` directive in the base apache config for `/nmag`.
https://askubuntu.com/questions/429869/is-this-a-correct-way-to-enable-htaccess-in-apache-2-4-7

Yeah, we can talk about it later.

**Comment by fangohr** [comment]
I have requested that the university sets up some forwarding.

**Comment by fangohr** [comment]
Redirection is now in place. :)
