### ISSUE TITLE
Put static html from Wiki into new github pages location

### ISSUE THREAD

**Issue by fangohr** [nmag-project/project-tasks#16]
The scraped and convert html is here: https://github.com/mhanberry1/nmag-www-archive/tree/master/nmag.soton.ac.uk

- This needs to be moved to http://nmag-project.github.io to be browsable
- Need to update link to Wiki in tabs on the left to point to the new location

@venkat004 - can you help?

**Comment by mhanberry1** [comment]
Done: https://nmag-project.github.io/community/wiki/nmag

The login/signup features don't work obviously.
