### ISSUE TITLE
Move Issues to the nmag-project org

### ISSUE THREAD

**Issue by mhanberry1** [nmag-project/project-tasks#18]
The existing issues on fangohr/nmag would be better suited as part of a project board in the nmag organization:
https://github.com/orgs/nmag-project/projects

Any issues that are outdated or otherwise not needed anymore should not be moved to the new location. Instead mark them as done or abandoned.

**Comment by fangohr** [comment]
I think we need a repo to host issues. Suggestions for a name?

**Comment by mhanberry1** [comment]
If the issues are relate to the web-migration effort, then maybe they should be on https://github.com/nmag-project/nmag-project.github.io?
