### ISSUE TITLE
Save information from Wiki (https://nmag.soton.ac.uk/community/wiki/nmag)

### ISSUE THREAD

**Issue by fangohr** [nmag-project/project-tasks#4]
The server running https://nmag.soton.ac.uk/community/wiki/nmag has to shut down.

We should preserve the information on there.

Options:

- Wiki content needs to be converted into static html, and added to documentation () or webpages() or similar place
   - extraction of the information: may be this can be done with a web crawler, or one needs to go through all pages manually
   - putting this into static html:
     - either as a dump of "what used to be in the wiki" [this is easier and maybe better]
     - or process the information and insert in right place in documentation

- Or convert content of Wiki into Github Wiki page (for example for this Wiki https://github.com/fangohr/nmag/wiki). 
  -  I don't know if this is easy or hard

Review:
- it may turn out that some pages are out of date, then in principle we could discard them.

**Comment by mhanberry1** [comment]
@fangohr

> Wiki content needs to be converted into static html

I've archived the nmag site here:
https://github.com/mhanberry1/nmag-www-archive

The wiki is located in nmag.soton.ac.uk/community/wiki/nmag

> convert content of Wiki into Github Wiki page

I think this is a good idea. I can work on migrating the content to github.

**Comment by fangohr** [comment]
Great, thanks. Ideally, we integrate it with the documentation eventually. (Maybe have an extra chapter: "Wiki contents from 2019" or so?)

**Comment by fangohr** [comment]
The Wiki has now been moved to https://github.com/nmag-project/wiki/wiki
